# -*- mode: ruby -*-
# vi: set ft=ruby :

# Constants from config file
# Do not change these values from here. Consult config json file.
DEFAULT_USER = "default_user"
DEFAULT_PASS = "default_pass"
VAGRANTFILE_API_VERSION = "2"
DISK_SIZE = "disk_size"

# Constants from command line parameters
VAGRANT_IMAGE = "default_image"
HOSTNAME = "default_hostname"
VB_NAME = "default_vbname"
SSH_INSERT_KEY = "ssh_insert_key"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = VAGRANT_IMAGE
    config.ssh.username = DEFAULT_USER
    config.ssh.password = DEFAULT_PASS
    config.ssh.insert_key = SSH_INSERT_KEY
    config.vm.hostname = HOSTNAME
    config.vm.define HOSTNAME
    config.vm.provider :virtualbox do |vb|
        vb.name = VB_NAME
        # GNS3: serial configuration to be able to connect via console
        vb.customize ["modifyvm", :id, "--uart1", "0x3f8", "4"]
    end
